const STATUS_TONES = {
  ACTIVE: 'success',
  APPROVED: 'success',
  RESOLVED: 'success',
  OPEN: 'warning',
  PENDING: 'warning',
  IN_PROGRESS: 'secondary',
  LIMITED: 'secondary',
  CANCELLED: 'danger',
  CLOSED: 'neutral',
  REJECTED: 'danger',
  OUT_OF_SERVICE: 'danger',
  BOOKING: 'primary',
  COMMENT: 'warning',
  SYSTEM: 'neutral',
  USER: 'primary',
  ADMIN: 'secondary',
  TECHNICIAN: 'warning',
  STUDENT: 'primary',
  ALL: 'neutral',
  AUTH: 'primary',
  RESOURCE: 'secondary',
  TICKET: 'warning',
  WEB: 'secondary',
  EMAIL: 'primary',
  BOTH: 'success',
  UNREAD: 'warning',
  READ: 'success',
  LOW: 'secondary',
  NORMAL: 'primary',
  HIGH: 'danger',
};

export function getStatusTone(status = '') {
  return STATUS_TONES[status] ?? 'neutral';
}
