spring.application.name=smart-campus-backend
server.port=8081

spring.data.mongodb.uri=mongodb+srv://Nodes4:qLcGIyKxANspMX6k@cluster0.aqtqhkj.mongodb.net/smart_campus_db?retryWrites=true&w=majority&appName=Cluster0
