spring.application.name=smart-campus-backend
server.port=8080

# MongoDB
spring.data.mongodb.uri=mongodb+srv://Nodes4:qLcGIyKxANspMX6k@cluster0.aqtqhkj.mongodb.net/smart_campus_db?retryWrites=true&w=majority&appName=Cluster0

# Google OAuth 2.0
spring.security.oauth2.client.registration.google.client-id=367887723685-14js8j0bn70v4orpfmrns9ccsi3mormd.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
